name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          # Một số VPS cần cấu hình này nếu dùng password
          envs: GITHUB_SHA
          script: |
            echo "--- Dang ket noi vao VPS ---"
            cd ${{ secrets.PROJECT_PATH }}
            
            echo "--- Dang cap nhat code ---"
            git pull origin main
            
            echo "--- Dang khoi dong lai Docker ---"
            docker compose up -d --build
            
            echo "--- Dang don dep image cu ---"
            docker image prune -f
            
            echo "--- Deploy Thanh Cong! ---"
